import React from 'react';
import { createRoot } from 'react-dom/client';
import { createInertiaApp } from '@inertiajs/react';
import '@fontsource/barlow-condensed/600.css';
import '@fontsource/barlow-condensed/700.css';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '../css/app.css';
import '../css/hero.css';
import Store from './Pages/Store';
import Catalog from './Pages/Catalog';
import Workshop from './Pages/Workshop';
import ProductDetail from './Pages/ProductDetail';
import AdminLogin from './Pages/Admin/Login';
import AdminDashboard from './Pages/Admin/Dashboard';
import AdminProducts from './Pages/Admin/Products';
import AdminProductForm from './Pages/Admin/ProductForm';
import AdminCategories from './Pages/Admin/Categories';
import AdminStats from './Pages/Admin/Stats';
import AdminAudit from './Pages/Admin/Audit';
import AdminMessages from './Pages/Admin/Messages';
const pages = { Store, Catalog, Workshop, ProductDetail, 'Admin/Login': AdminLogin, 'Admin/Dashboard': AdminDashboard, 'Admin/Products': AdminProducts, 'Admin/ProductForm': AdminProductForm, 'Admin/Categories': AdminCategories, 'Admin/Stats': AdminStats, 'Admin/Audit': AdminAudit, 'Admin/Messages': AdminMessages };
createInertiaApp({ resolve: name => pages[name], setup({ el, App, props }) { createRoot(el).render(<App {...props} />); } });
